name: go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: set up go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: build
      run: go build -v ./...

    # no tests, at least for now...
    # - name: Test
    #   run: go test -v ./...
